#!/usr/bin/env bash
# Transfers a file from client to a server
# Accepts 4 Parameters
# 1 path of file to be trsnsferred
# 2 IP of server 
# 3 usrename scp connects with
# 4 path to the SSH private key
if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$4" -o stricthostkeychecking=no "$1" "$3@$2":~/
fi 
