#!/usr/bin/env bash
# The script displays "Best School" 10 times but for the 9th iteration displays "Best School" and the "Hi"
i=1
name="Best School"
while [ $i -le 10 ]
do
	echo $name
	if [[ $i -eq 9 ]]
	then
		echo "Hi"
	fi
	i=$((i+1))
done
