#!/usr/bin/env bash
# This script displays "bad luck" on 4th loop.
# "good luck" on 8th loop
# "Best School" on every other line up to 10 lines
i=1
while [ $i -le 10 ]; do
      if [ $i -eq 4 ]
      then
	echo "bad luck"
      elif [ $i -eq 8 ]
      then
	echo "good luck"
      else
	echo "Best School"
      fi
      let i+=1
done
