#!/usr/bin/env bash
# The script loops from 1 to 10 display "bad luck" for the 4th loop "good luck" 
# for the 8th and "Best School" for the other iterations
i=0
while [ $i -lt 10 ]; do
	if (( i == 4 )); then
		echo "bad luck"
	elif (( i == 8 )); then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
